name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Create .env file
      run: cp .env.example .env

    - name: Run black formatter
      run: |
        source .venv/bin/activate
        echo "Running black... if this fails, run `python -m black .` to fix the issues"
        python -m black --check . # If this fails, run `python -m black .` to fix the issues

    - name: Run flake8 linter
      run: |
        source .venv/bin/activate
        flake8 .

    - name: Run tests with coverage
      run: |
        source .venv/bin/activate
        pytest --cov=main --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}